Make filepath a positional argument

diff --git a/pat_explore b/pat_explore
--- a/pat_explore
+++ b/pat_explore
@@ -3,12 +3,11 @@
 usage=$(cat << EOF
 Pat: An HTTP API development toolkit
 
-Usage: $0 [OPTIONS]
+Usage: $0 [OPTIONS] FILEPATH
 It runs HTTP requests specified in a file
 and runs them.
 
 Supported options:
-    * -f: Filepath to run requests from (default present dir)
     * -s: Open the response in a terminal pager
         The response is piped to a terminal pager.
         You can specify your own with the TERM_PAGE variable.
@@ -31,7 +30,12 @@ NC='\033[0m' # No Color
 GREEN='\033[0;32m'
 YELLOW='\033[1;33m'
 
-filepath=`pwd`
+if [ -z "$1" ]; then
+    echo "Error: filepath not specified"
+    echo "$usage"
+    exit 1
+fi
+
 curl_args=""
 # TODO: Add option to show curl progress
 curl_progress=false
@@ -40,7 +44,6 @@ pretty_print=false
 while getopts f:hps opt; do
     case $opt in
         h) echo "$usage"; exit;;
-        f) $filepath=${OPTARG};;
         p) pretty_print=true;;
         s) scroll_mode=true;;
         :) echo "Missing argument for option -$OPTARG"; echo "$usage"; exit 1;;
@@ -63,6 +66,8 @@ if ! "$curl_progress"; then
 fi
 
 shift $(( OPTIND - 1 ))
+filepath="$1"
+shift 1
 
 exit_code=0
 requests=(`find "$filepath" -type f -path "*.curlf" -and -not -path "$0"`)
